// <auto-generated />
using DoAn5API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAn5API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201027030431_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoAn5API.Models.Phim", b =>
                {
                    b.Property<string>("MaPhim")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Anh");

                    b.Property<int>("LuotXem");

                    b.Property<int>("Nam");

                    b.Property<string>("NoiDung");

                    b.Property<string>("SoTap");

                    b.Property<string>("TenPhim");

                    b.HasKey("MaPhim");

                    b.ToTable("Phims");
                });
#pragma warning restore 612, 618
        }
    }
}
